### ISSUE TITLE
Fix 'no repositories' for an account that has installed our Github Bot

### ISSUE THREAD

**Issue by garrettmaring** [engi-network/engi-blockchain-gql#120]
My staging account (address: 5DwEr2QQ6o9AKPvdjysCr8jnGRU1KxUssEBTU1Zm7xjidw4o) has been configured (installed our Github App) yet shows no selectable repositories in the creation UI.

<img width="541" alt="Screenshot 2023-10-04 at 11 56 31 AM" src="https://github.com/engi-network/engi-blockchain-gql/assets/8270120/72edb784-adac-4eba-9eea-51997789784a">

<img width="605" alt="Screenshot 2023-10-04 at 11 48 45 AM" src="https://github.com/engi-network/engi-blockchain-gql/assets/8270120/cd829553-48d3-48ff-931f-e9fe1db0dcf3">

**Comment by garrettmaring** [comment]
@jfwu90 do we have a separate staging Github App now? I think the staging web is still pointing to the production one if so (and maybe causing this mismatch between being installed vs. showing no repositories available)

<img width="884" alt="Screenshot 2023-10-04 at 11 58 18 AM" src="https://github.com/engi-network/engi-blockchain-gql/assets/8270120/a3c0d0fe-e655-45bc-ad6b-325ba969548d">

**Comment by jfwu90** [comment]
No separate staging github app, but you need to edit the callback URL to use staging instead or production.
