### ISSUE TITLE
Add service to return patchfile for a claim/attempt

### ISSUE THREAD

**Issue by garrettmaring** [engi-network/engi-blockchain-gql#159]
Support users attempting bounties from the UI. An hosted patchfile URL is currently created locally by the CLI when a user is making an attempt. Replicate that behavior API side (generate + store patchfiles) and expose the ability to generate (and return the URL) such that a user 'click-to-claim'.

The API will generate a patchfile for a given user-fork and original bounty repo and return that URL to the client. The user can then initiate an attempt transaction and sign it with a compatible extension.

**Comment by jfwu90** [comment]
User to provide repo, branch, and commit as args in a gql mutation to generate a patchfile URL.

**Comment by garrettmaring** [comment]
believe this is done
