### ISSUE TITLE
add better error handling when auth has expired or is missing

### ISSUE THREAD

**Issue by jfwu90** [engi-network/engi-blockchain-gql#177]
When auth is expired or missing, GQL will return a `NULL_REFERENCE` error with no indications that auth is the issue. Can the error be something that indicates auth is invalid?

**Comment by georgiosd** [comment]
Can you give me a repro here? Are you talking about invoking an authenticated query with an expired/missing token?

**Comment by jfwu90** [comment]
Closing for now.
