### ISSUE TITLE
Add field for searching for jobs attempted/claimed by a user

### ISSUE THREAD

**Issue by jfwu90** [engi-network/engi-blockchain-gql#181]
On the user bounties page, there will be two tables: bounties created by user, bounties attempted/claimed by user

There needs to be a way to search for bounties attempted by user.

**Comment by georgiosd** [comment]
I've added an `attemptedBy` field to query on users who have attempted a job
![image](https://github.com/engi-network/engi-blockchain-gql/assets/1672054/5c518427-6a24-4cdf-b5ec-7130ba55393c)

I also repurposed the unused `CreatedOrSolvedBy` to `RelevantToCurrentUser` to get all jobs that are created/solved/attempted by the current user. Careful, it will throw if you include the flag but you don't send auth info.
![image](https://github.com/engi-network/engi-blockchain-gql/assets/1672054/31d555cc-4071-4c8b-b3a4-b0f2b567f921)

https://github.com/engi-network/engi-blockchain-gql/commit/bc2e90b057609af0ae3433f5285d393d300904b3
